/* ==========================================================================
   سوق الكويت القديم - قاعدة بيانات المنتجات التجريبية
   Old Kuwait Market - Demo Products Data (50+ products)
   ملاحظة: الصور هنا عبارة عن صور بديلة (Placeholder) مصممة بألوان الموقع
   ومكتوب عليها اسم كل قطعة، لضمان عرض صورة مناسبة لكل منتج دون كسر الروابط.
   يوصى باستبدالها بصور تصوير حقيقية للمنتجات قبل النشر الفعلي.
   ========================================================================== */

// ---------- الأقسام العشرة ----------
const CATEGORIES = [
  { id: 'dallah',    name: 'دلال وأباريق',       nameEn: 'Coffee Pots & Jugs',   icon: 'fa-mug-hot',        color: '#C6952C' },
  { id: 'sadu',      name: 'السدو والمنسوجات',     nameEn: 'Sadu & Textiles',      icon: 'fa-vector-square',  color: '#6B4423' },
  { id: 'coins',     name: 'العملات القديمة',      nameEn: 'Old Coins',            icon: 'fa-coins',          color: '#A97B1F' },
  { id: 'stamps',    name: 'الطوابع',              nameEn: 'Stamps',               icon: 'fa-stamp',          color: '#8B6B3D' },
  { id: 'watches',   name: 'الساعات القديمة',      nameEn: 'Antique Watches',      icon: 'fa-clock',          color: '#4A2E17' },
  { id: 'furniture', name: 'الأثاث التراثي',       nameEn: 'Heritage Furniture',   icon: 'fa-chair',          color: '#6B4423' },
  { id: 'maritime',  name: 'الأدوات البحرية',      nameEn: 'Maritime Tools',       icon: 'fa-anchor',         color: '#3E2A1A' },
  { id: 'antiques',  name: 'التحف',                nameEn: 'Antiques',             icon: 'fa-gem',            color: '#C6952C' },
  { id: 'clothing',  name: 'الملابس التراثية',     nameEn: 'Heritage Clothing',    icon: 'fa-vest',           color: '#A97B1F' },
  { id: 'rare',      name: 'المقتنيات النادرة',    nameEn: 'Rare Collectibles',    icon: 'fa-crown',          color: '#8B6B3D' },
];

// دالة لإنشاء رابط صورة بديلة موسومة باسم المنتج بألوان الهوية
function ph(text, bg, i) {
  const seed = encodeURIComponent(text + (i || ''));
  const color = (bg || 'C6952C').replace('#', '');
  return `https://placehold.co/600x600/${color}/FDF8EE?text=${seed}&font=tajawal`;
}

// ---------- بيانات المنتجات (أكثر من 50 منتج) ----------
const PRODUCTS = [
  // ===== دلال وأباريق =====
  { id: 1, category: 'dallah', title: 'دلة قهوة نحاسية يدوية الصنع', titleEn: 'Handcrafted Copper Coffee Pot', price: 45, oldPrice: 60, rating: 4.8, reviews: 24, condition: 'مستعمل - حالة ممتازة', age: 'يعود لخمسينيات القرن الماضي', material: 'نحاس أصفر', origin: 'الكويت', seller: 'أحمد البدر', featured: true, auction: false, desc: 'دلة قهوة عربية أصيلة مصنوعة يدويًا من النحاس الأصفر، محفورة بنقوش تراثية دقيقة، تعكس أصالة الضيافة الكويتية القديمة.' },
  { id: 2, category: 'dallah', title: 'إبريق ماء نحاسي مزخرف', titleEn: 'Ornate Copper Water Jug', price: 32, oldPrice: null, rating: 4.5, reviews: 12, condition: 'مستعمل - حالة جيدة جدًا', age: 'يعود لستينيات القرن الماضي', material: 'نحاس', origin: 'الكويت', seller: 'فاطمة العتيبي', featured: false, auction: false, desc: 'إبريق ماء تقليدي بزخارف يدوية دقيقة، كان يستخدم في المجالس الكويتية القديمة لتقديم الماء للضيوف.' },
  { id: 3, category: 'dallah', title: 'طقم دلال قهوة (3 قطع)', titleEn: 'Three-Piece Coffee Pot Set', price: 120, oldPrice: 150, rating: 5.0, reviews: 31, condition: 'مستعمل - حالة ممتازة', age: 'مطلع القرن العشرين', material: 'نحاس مطلي فضة', origin: 'الكويت', seller: 'محمد الرشيدي', featured: true, auction: true, desc: 'طقم نادر من ثلاث دلال بأحجام متدرجة، تستخدم تقليديًا لتحضير القهوة العربية بمراحلها الثلاث.' },
  { id: 4, category: 'dallah', title: 'دلة قهوة صغيرة للتزيين', titleEn: 'Small Decorative Coffee Pot', price: 18, oldPrice: null, rating: 4.2, reviews: 8, condition: 'جديد - تراثي الطراز', age: 'صناعة حديثة بطراز تراثي', material: 'نحاس', origin: 'الكويت', seller: 'سوق الكويت القديم', featured: false, auction: false, desc: 'دلة صغيرة مثالية للديكور المنزلي بطراز تراثي أصيل، مناسبة للهدايا التذكارية.' },
  { id: 5, category: 'dallah', title: 'إبريق شاي نحاسي بمقبض خشبي', titleEn: 'Copper Teapot with Wooden Handle', price: 27, oldPrice: 35, rating: 4.6, reviews: 15, condition: 'مستعمل - حالة جيدة', age: 'سبعينيات القرن الماضي', material: 'نحاس وخشب', origin: 'الكويت', seller: 'سارة المطيري', featured: false, auction: false, desc: 'إبريق شاي تقليدي بمقبض خشبي مقاوم للحرارة، استُخدم في البيوت الكويتية القديمة.' },

  // ===== السدو والمنسوجات =====
  { id: 6, category: 'sadu', title: 'سجادة سدو يدوية الحياكة', titleEn: 'Handwoven Sadu Rug', price: 85, oldPrice: 110, rating: 4.9, reviews: 22, condition: 'مستعمل - حالة ممتازة', age: 'يعود لـ 40 عامًا', material: 'صوف طبيعي', origin: 'البادية الكويتية', seller: 'أم عبدالله', featured: true, auction: false, desc: 'سجادة سدو أصيلة منسوجة يدويًا بألوان تراثية زاهية، تمثل فن النسيج البدوي الكويتي العريق.' },
  { id: 7, category: 'sadu', title: 'وسادة مقعد بنقوش السدو', titleEn: 'Sadu-Patterned Floor Cushion', price: 22, oldPrice: null, rating: 4.4, reviews: 9, condition: 'جديد', age: 'صناعة حديثة', material: 'قطن وصوف', origin: 'الكويت', seller: 'ورشة السدو التراثية', featured: false, auction: false, desc: 'وسادة أرضية بنقوش السدو التقليدية، مثالية لإضافة لمسة تراثية للمجالس العصرية.' },
  { id: 8, category: 'sadu', title: 'بشت رجالي مطرز', titleEn: 'Embroidered Men\'s Bisht', price: 150, oldPrice: 190, rating: 5.0, reviews: 18, condition: 'مستعمل - حالة ممتازة', age: 'يعود لـ 30 عامًا', material: 'صوف وخيوط ذهبية', origin: 'الكويت', seller: 'عبدالعزيز الصانع', featured: true, auction: true, desc: 'بشت تقليدي مطرز بخيوط ذهبية، يرتديه الرجال في المناسبات الرسمية والأعراس.' },
  { id: 9, category: 'sadu', title: 'خرج سدو للتعليق', titleEn: 'Sadu Woven Wall Bag', price: 38, oldPrice: null, rating: 4.3, reviews: 6, condition: 'مستعمل - حالة جيدة', age: 'يعود لـ 25 عامًا', material: 'صوف', origin: 'البادية الكويتية', seller: 'نورة الهاجري', featured: false, auction: false, desc: 'خرج سدو تقليدي كان يستخدم لحمل الأغراض على الإبل، اليوم يُستخدم كقطعة ديكور جدارية.' },
  { id: 10, category: 'sadu', title: 'مفرش سدو للطاولة', titleEn: 'Sadu Table Runner', price: 15, oldPrice: 20, rating: 4.1, reviews: 5, condition: 'جديد', age: 'صناعة حديثة', material: 'قطن', origin: 'الكويت', seller: 'ورشة السدو التراثية', featured: false, auction: false, desc: 'مفرش طاولة أنيق بنقوش السدو الهندسية الملونة، يضيف لمسة تراثية لسفرة الطعام.' },

  // ===== العملات القديمة =====
  { id: 11, category: 'coins', title: 'مجموعة عملات كويتية فضية نادرة', titleEn: 'Rare Kuwaiti Silver Coin Set', price: 210, oldPrice: 260, rating: 4.9, reviews: 27, condition: 'حالة ممتازة - مصنّفة', age: 'إصدار 1961', material: 'فضة', origin: 'الكويت', seller: 'مركز العملات الكويتي', featured: true, auction: true, desc: 'مجموعة نادرة من العملات الفضية الكويتية الأولى بعد الاستقلال، محفوظة بحالة ممتازة داخل علبة عرض.' },
  { id: 12, category: 'coins', title: 'قطعة نقدية هندية قديمة متداولة بالخليج', titleEn: 'Old Gulf Rupee Coin', price: 40, oldPrice: null, rating: 4.5, reviews: 11, condition: 'مستعمل - حالة جيدة', age: 'خمسينيات القرن الماضي', material: 'نيكل', origin: 'الخليج العربي', seller: 'خالد النجدي', featured: false, auction: false, desc: 'عملة كانت متداولة في الكويت والخليج قبل إصدار الدينار الكويتي، قطعة تاريخية مهمة لهواة الجمع.' },
  { id: 13, category: 'coins', title: 'دينار كويتي تذكاري إصدار خاص', titleEn: 'Commemorative Kuwaiti Dinar Coin', price: 95, oldPrice: 115, rating: 4.8, reviews: 19, condition: 'جديد - إصدار محدود', age: 'إصدار تذكاري', material: 'نحاس ونيكل', origin: 'الكويت', seller: 'بنك الكويت المركزي (توزيع تجاري)', featured: true, auction: false, desc: 'عملة تذكارية أصدرت بمناسبة وطنية، مصنوعة بجودة عالية ومحفوظة في علبة أصلية.' },
  { id: 14, category: 'coins', title: 'ألبوم عملات قديمة متنوعة', titleEn: 'Vintage Mixed Coin Album', price: 130, oldPrice: null, rating: 4.6, reviews: 14, condition: 'مستعمل - مجموعة كاملة', age: 'متنوع 1940-1970', material: 'معادن متعددة', origin: 'الكويت والخليج', seller: 'عيسى الكندري', featured: false, auction: true, desc: 'ألبوم يضم 25 قطعة نقدية متنوعة من حقب زمنية مختلفة، مرتبة ومصنفة بعناية لهواة الجمع.' },
  { id: 15, category: 'coins', title: 'عملة برونزية نادرة', titleEn: 'Rare Bronze Coin', price: 55, oldPrice: 70, rating: 4.3, reviews: 7, condition: 'مستعمل - حالة جيدة', age: 'أوائل القرن العشرين', material: 'برونز', origin: 'الخليج العربي', seller: 'مركز العملات الكويتي', featured: false, auction: false, desc: 'عملة برونزية نادرة من أوائل القرن الماضي، تحمل نقوشًا تاريخية مميزة.' },

  // ===== الطوابع =====
  { id: 16, category: 'stamps', title: 'ألبوم طوابع الكويت التاريخية', titleEn: 'Historical Kuwait Stamp Album', price: 75, oldPrice: 95, rating: 4.7, reviews: 16, condition: 'حالة ممتازة', age: '1950-1980', material: 'ورق مطبوع', origin: 'الكويت', seller: 'نادي هواة الطوابع', featured: true, auction: false, desc: 'ألبوم كامل يضم طوابع بريدية كويتية نادرة تعود لعقود مختلفة، بحالة حفظ ممتازة.' },
  { id: 17, category: 'stamps', title: 'طابع تذكاري لاستقلال الكويت', titleEn: 'Kuwait Independence Commemorative Stamp', price: 28, oldPrice: null, rating: 4.9, reviews: 21, condition: 'حالة ممتازة - نادر', age: 'إصدار 1961', material: 'ورق', origin: 'الكويت', seller: 'نادي هواة الطوابع', featured: true, auction: true, desc: 'طابع بريدي نادر صدر احتفالًا باستقلال دولة الكويت، قطعة تاريخية مهمة لهواة الجمع.' },
  { id: 18, category: 'stamps', title: 'مجموعة طوابع بريدية بحرية', titleEn: 'Maritime-Themed Stamp Collection', price: 34, oldPrice: 42, rating: 4.4, reviews: 9, condition: 'حالة جيدة جدًا', age: 'ستينيات القرن الماضي', material: 'ورق', origin: 'الكويت', seller: 'يوسف العنزي', featured: false, auction: false, desc: 'مجموعة طوابع تصور السفن والغوص واللؤلؤ، توثق تاريخ الكويت البحري العريق.' },
  { id: 19, category: 'stamps', title: 'طابع بريدي نادر بخط عربي', titleEn: 'Rare Arabic Calligraphy Stamp', price: 19, oldPrice: null, rating: 4.2, reviews: 5, condition: 'حالة جيدة', age: 'سبعينيات القرن الماضي', material: 'ورق', origin: 'الكويت', seller: 'نادي هواة الطوابع', featured: false, auction: false, desc: 'طابع مزين بخط عربي جميل، من إصدارات الكويت البريدية القديمة.' },
  { id: 20, category: 'stamps', title: 'علبة طوابع دبلوماسية قديمة', titleEn: 'Old Diplomatic Stamp Box Set', price: 60, oldPrice: 75, rating: 4.6, reviews: 12, condition: 'حالة ممتازة', age: '1965-1975', material: 'ورق وعلبة معدنية', origin: 'الكويت', seller: 'عيسى الكندري', featured: false, auction: false, desc: 'علبة معدنية أنيقة تحتوي على مجموعة طوابع دبلوماسية نادرة محفوظة بعناية.' },

  // ===== الساعات القديمة =====
  { id: 21, category: 'watches', title: 'ساعة جيب ذهبية عتيقة', titleEn: 'Antique Gold Pocket Watch', price: 180, oldPrice: 220, rating: 4.8, reviews: 20, condition: 'مستعمل - تعمل بكفاءة', age: 'أوائل القرن العشرين', material: 'ذهب مطلي', origin: 'أوروبا (متداولة بالكويت)', seller: 'ناصر الفضلي', featured: true, auction: true, desc: 'ساعة جيب ذهبية أنيقة كانت رمزًا للمكانة الاجتماعية، لا تزال تعمل بدقة حتى اليوم.' },
  { id: 22, category: 'watches', title: 'ساعة حائط خشبية بنظام البندول', titleEn: 'Wooden Pendulum Wall Clock', price: 95, oldPrice: null, rating: 4.5, reviews: 13, condition: 'مستعمل - حالة جيدة جدًا', age: 'ستينيات القرن الماضي', material: 'خشب وزجاج', origin: 'أوروبا', seller: 'بيت التحف الكويتي', featured: false, auction: false, desc: 'ساعة حائط كلاسيكية بنظام البندول المتحرك، قطعة ديكور فاخرة تناسب المجالس التراثية.' },
  { id: 23, category: 'watches', title: 'ساعة يد رجالية سويسرية قديمة', titleEn: 'Vintage Swiss Men\'s Wristwatch', price: 240, oldPrice: 300, rating: 4.9, reviews: 25, condition: 'مستعمل - تعمل بكفاءة', age: 'سبعينيات القرن الماضي', material: 'ستانلس ستيل وجلد', origin: 'سويسرا', seller: 'ناصر الفضلي', featured: true, auction: true, desc: 'ساعة يد سويسرية أصلية بحركة ميكانيكية دقيقة، من أشهر الساعات المقتناة في تلك الحقبة.' },
  { id: 24, category: 'watches', title: 'ساعة طاولة نحاسية عتيقة', titleEn: 'Antique Brass Desk Clock', price: 65, oldPrice: 80, rating: 4.3, reviews: 8, condition: 'مستعمل - حالة جيدة', age: 'خمسينيات القرن الماضي', material: 'نحاس', origin: 'أوروبا', seller: 'بيت التحف الكويتي', featured: false, auction: false, desc: 'ساعة طاولة نحاسية بتصميم كلاسيكي أنيق، تضيف لمسة فخامة لأي مكتب أو رف عرض.' },
  { id: 25, category: 'watches', title: 'ساعة رملية خشبية تراثية', titleEn: 'Traditional Wooden Hourglass', price: 22, oldPrice: null, rating: 4.0, reviews: 6, condition: 'جديد - طراز تراثي', age: 'صناعة حديثة', material: 'خشب وزجاج', origin: 'الكويت', seller: 'سوق الكويت القديم', featured: false, auction: false, desc: 'ساعة رملية بإطار خشبي تقليدي، قطعة ديكور جميلة تذكرنا بالطرق القديمة لقياس الوقت.' },

  // ===== الأثاث التراثي =====
  { id: 26, category: 'furniture', title: 'صندوق خشبي مطعّم بالنحاس', titleEn: 'Brass-Inlaid Wooden Chest', price: 210, oldPrice: 260, rating: 4.9, reviews: 23, condition: 'مستعمل - حالة ممتازة', age: 'يعود لـ 70 عامًا', material: 'خشب الساج والنحاس', origin: 'الكويت والهند', seller: 'بيت التحف الكويتي', featured: true, auction: true, desc: 'صندوق تراثي فاخر مطعّم بزخارف نحاسية دقيقة، كان يستخدم لحفظ المقتنيات الثمينة والمجوهرات.' },
  { id: 27, category: 'furniture', title: 'كرسي مجلس خشبي منجّد', titleEn: 'Upholstered Wooden Majlis Chair', price: 140, oldPrice: null, rating: 4.6, reviews: 14, condition: 'مستعمل - حالة جيدة جدًا', age: 'يعود لـ 40 عامًا', material: 'خشب وقماش مطرز', origin: 'الكويت', seller: 'عبدالله الشمري', featured: false, auction: false, desc: 'كرسي مجلس تقليدي بحفر خشبي يدوي وتنجيد مطرز، مثالي لمجالس الضيافة التراثية.' },
  { id: 28, category: 'furniture', title: 'طاولة قهوة خشبية بنقوش يدوية', titleEn: 'Hand-Carved Wooden Coffee Table', price: 175, oldPrice: 210, rating: 4.7, reviews: 17, condition: 'مستعمل - حالة ممتازة', age: 'يعود لـ 50 عامًا', material: 'خشب الجوز', origin: 'الكويت', seller: 'عبدالله الشمري', featured: true, auction: false, desc: 'طاولة أنيقة محفورة يدويًا بنقوش هندسية إسلامية، قطعة مركزية مثالية لأي مجلس.' },
  { id: 29, category: 'furniture', title: 'مرآة تراثية بإطار خشبي منقوش', titleEn: 'Ornate Wooden Framed Mirror', price: 88, oldPrice: null, rating: 4.4, reviews: 10, condition: 'مستعمل - حالة جيدة', age: 'يعود لـ 45 عامًا', material: 'خشب وزجاج', origin: 'الكويت', seller: 'مريم العدواني', featured: false, auction: false, desc: 'مرآة كلاسيكية بإطار خشبي منقوش يدويًا، تضيف طابعًا تراثيًا أنيقًا لأي غرفة.' },
  { id: 30, category: 'furniture', title: 'رف عرض خشبي للتحف', titleEn: 'Wooden Display Shelf for Antiques', price: 62, oldPrice: 78, rating: 4.2, reviews: 7, condition: 'مستعمل - حالة جيدة', age: 'يعود لـ 30 عامًا', material: 'خشب', origin: 'الكويت', seller: 'عبدالله الشمري', featured: false, auction: false, desc: 'رف خشبي متعدد الطبقات مثالي لعرض التحف والمقتنيات التراثية الصغيرة.' },

  // ===== الأدوات البحرية =====
  { id: 31, category: 'maritime', title: 'بوصلة بحرية نحاسية قديمة', titleEn: 'Antique Brass Ship Compass', price: 130, oldPrice: 160, rating: 4.8, reviews: 19, condition: 'مستعمل - تعمل بكفاءة', age: 'يعود لـ 60 عامًا', material: 'نحاس وزجاج', origin: 'الكويت', seller: 'كابتن سعود الرومي', featured: true, auction: true, desc: 'بوصلة بحرية أصلية كانت تستخدم على متن سفن الغوص واللؤلؤ الكويتية القديمة.' },
  { id: 32, category: 'maritime', title: 'نموذج سفينة شراعية (بوم) مصغر', titleEn: 'Miniature Dhow Boat Model', price: 95, oldPrice: null, rating: 4.9, reviews: 26, condition: 'جديد - صناعة يدوية', age: 'صناعة حرفية حديثة', material: 'خشب وقماش شراعي', origin: 'الكويت', seller: 'ورشة النجارة البحرية', featured: true, auction: false, desc: 'نموذج مصغر دقيق لسفينة "البوم" الكويتية التقليدية، مصنوع يدويًا بحرفية عالية.' },
  { id: 33, category: 'maritime', title: 'أدوات غوص تقليدية (فطام ومنخار)', titleEn: 'Traditional Pearl Diving Tools Set', price: 55, oldPrice: 68, rating: 4.5, reviews: 11, condition: 'مستعمل - حالة جيدة', age: 'يعود لـ 55 عامًا', material: 'قرن وجلد', origin: 'الكويت', seller: 'كابتن سعود الرومي', featured: false, auction: false, desc: 'طقم أدوات الغوص التقليدية التي كان يستخدمها الغواصون الكويتيون في رحلات صيد اللؤلؤ.' },
  { id: 34, category: 'maritime', title: 'مصباح سفينة نحاسي قديم', titleEn: 'Old Brass Ship Lantern', price: 70, oldPrice: null, rating: 4.6, reviews: 13, condition: 'مستعمل - حالة جيدة جدًا', age: 'يعود لـ 65 عامًا', material: 'نحاس وزجاج', origin: 'الكويت', seller: 'يعقوب الصايغ', featured: false, auction: false, desc: 'مصباح إضاءة كان يُعلق على السفن الشراعية القديمة، لا يزال يحتفظ ببريقه الأصلي.' },
  { id: 35, category: 'maritime', title: 'صندوق أدوات صيد اللؤلؤ', titleEn: 'Pearl Diving Equipment Box', price: 110, oldPrice: 135, rating: 4.7, reviews: 15, condition: 'مستعمل - حالة ممتازة', age: 'يعود لـ 70 عامًا', material: 'خشب ومعدن', origin: 'الكويت', seller: 'كابتن سعود الرومي', featured: false, auction: true, desc: 'صندوق تراثي كامل يحتوي على أدوات صيد اللؤلؤ الأصلية، قطعة نادرة توثق تاريخ الكويت البحري.' },

  // ===== التحف =====
  { id: 36, category: 'antiques', title: 'مبخرة نحاسية مزخرفة', titleEn: 'Ornate Brass Incense Burner', price: 48, oldPrice: 60, rating: 4.7, reviews: 18, condition: 'مستعمل - حالة ممتازة', age: 'يعود لـ 50 عامًا', material: 'نحاس', origin: 'الكويت', seller: 'هدى الرشيد', featured: true, auction: false, desc: 'مبخرة تراثية بنقوش يدوية دقيقة، تستخدم لتبخير المجالس بالعود والبخور الفاخر.' },
  { id: 37, category: 'antiques', title: 'صندوق مجوهرات خشبي مطعّم بالصدف', titleEn: 'Mother-of-Pearl Inlaid Jewelry Box', price: 92, oldPrice: 115, rating: 4.9, reviews: 22, condition: 'مستعمل - حالة ممتازة', age: 'يعود لـ 60 عامًا', material: 'خشب وصدف', origin: 'الكويت', seller: 'هدى الرشيد', featured: true, auction: true, desc: 'صندوق تراثي فاخر مطعّم بالصدف الطبيعي بزخارف هندسية دقيقة، تحفة يدوية أصيلة.' },
  { id: 38, category: 'antiques', title: 'مصباح زيتي نحاسي قديم', titleEn: 'Antique Brass Oil Lamp', price: 36, oldPrice: null, rating: 4.4, reviews: 9, condition: 'مستعمل - حالة جيدة', age: 'يعود لـ 55 عامًا', material: 'نحاس', origin: 'الكويت', seller: 'يعقوب الصايغ', featured: false, auction: false, desc: 'مصباح زيتي تقليدي كان يُستخدم للإضاءة في البيوت الكويتية القديمة قبل انتشار الكهرباء.' },
  { id: 39, category: 'antiques', title: 'قدر طبخ نحاسي كبير', titleEn: 'Large Copper Cooking Pot', price: 58, oldPrice: 72, rating: 4.5, reviews: 12, condition: 'مستعمل - حالة جيدة جدًا', age: 'يعود لـ 45 عامًا', material: 'نحاس', origin: 'الكويت', seller: 'أم عبدالله', featured: false, auction: false, desc: 'قدر نحاسي تقليدي كبير الحجم كان يستخدم في تحضير الولائم الكويتية الكبيرة.' },
  { id: 40, category: 'antiques', title: 'تمثال جمل نحاسي تراثي', titleEn: 'Brass Camel Statuette', price: 26, oldPrice: null, rating: 4.3, reviews: 8, condition: 'جديد - طراز تراثي', age: 'صناعة حرفية حديثة', material: 'نحاس', origin: 'الكويت', seller: 'سوق الكويت القديم', featured: false, auction: false, desc: 'تمثال جمل نحاسي مصقول يدويًا، رمز تراثي جميل يناسب رفوف العرض والمكاتب.' },

  // ===== الملابس التراثية =====
  { id: 41, category: 'clothing', title: 'ثوب نسائي مطرز بخيوط ذهبية', titleEn: 'Gold-Embroidered Women\'s Thobe', price: 130, oldPrice: 160, rating: 4.9, reviews: 24, condition: 'مستعمل - حالة ممتازة', age: 'يعود لـ 35 عامًا', material: 'حرير وخيوط ذهبية', origin: 'الكويت', seller: 'مريم العدواني', featured: true, auction: false, desc: 'ثوب نسائي تقليدي (الدراعة) مطرز يدويًا بخيوط ذهبية فاخرة، يُلبس في المناسبات الخاصة.' },
  { id: 42, category: 'clothing', title: 'غترة وعقال رجالي تراثي', titleEn: 'Traditional Ghutra & Agal Set', price: 45, oldPrice: null, rating: 4.6, reviews: 14, condition: 'مستعمل - حالة جيدة جدًا', age: 'يعود لـ 20 عامًا', material: 'قطن وصوف', origin: 'الكويت', seller: 'عبدالعزيز الصانع', featured: false, auction: false, desc: 'طقم غترة وعقال أصيل بجودة عالية، قطعة أساسية من الزي التراثي الكويتي الرجالي.' },
  { id: 43, category: 'clothing', title: 'بخنق نسائي تراثي مطرز', titleEn: 'Embroidered Traditional Bukhnug', price: 68, oldPrice: 85, rating: 4.7, reviews: 11, condition: 'مستعمل - حالة ممتازة', age: 'يعود لـ 40 عامًا', material: 'قماش مطرز', origin: 'الكويت', seller: 'مريم العدواني', featured: false, auction: false, desc: 'بخنق نسائي تقليدي بتطريز يدوي ملون، يمثل جزءًا من الزي التراثي الكويتي القديم.' },
  { id: 44, category: 'clothing', title: 'دشداشة رجالية قطنية كلاسيكية', titleEn: 'Classic Cotton Men\'s Dishdasha', price: 38, oldPrice: null, rating: 4.4, reviews: 9, condition: 'مستعمل - حالة جيدة', age: 'يعود لـ 15 عامًا', material: 'قطن', origin: 'الكويت', seller: 'عبدالعزيز الصانع', featured: false, auction: false, desc: 'دشداشة قطنية بتفصيل تقليدي كلاسيكي، مريحة وأنيقة للاستخدام اليومي.' },
  { id: 45, category: 'clothing', title: 'حذاء نعال جلدي تراثي (يماني)', titleEn: 'Traditional Leather Yamani Sandals', price: 24, oldPrice: 30, rating: 4.2, reviews: 6, condition: 'جديد', age: 'صناعة حرفية حديثة', material: 'جلد طبيعي', origin: 'الكويت', seller: 'ورشة الجلود التراثية', featured: false, auction: false, desc: 'نعال جلدي تقليدي مصنوع يدويًا بطريقة الحرفيين القدامى، مريح ومتين.' },

  // ===== المقتنيات النادرة =====
  { id: 46, category: 'rare', title: 'خنجر تراثي بمقبض فضي منقوش', titleEn: 'Silver-Handled Heritage Dagger', price: 320, oldPrice: 380, rating: 5.0, reviews: 29, condition: 'مستعمل - حالة ممتازة', age: 'يعود لـ 80 عامًا', material: 'فضة وحديد', origin: 'الكويت', seller: 'بيت التحف الكويتي', featured: true, auction: true, desc: 'خنجر تراثي نادر بمقبض فضي منقوش يدويًا بدقة عالية، قطعة مقتنيات استثنائية للهواة الجادين.' },
  { id: 47, category: 'rare', title: 'مخطوطة قديمة مكتوبة بخط اليد', titleEn: 'Antique Handwritten Manuscript', price: 260, oldPrice: null, rating: 4.9, reviews: 20, condition: 'حالة حفظ جيدة جدًا', age: 'يعود لأكثر من 100 عام', material: 'ورق وجلد', origin: 'الكويت والمنطقة', seller: 'مكتبة التراث النادر', featured: true, auction: true, desc: 'مخطوطة تاريخية نادرة مكتوبة بخط اليد، محفوظة بعناية فائقة، توثق جانبًا من التراث الفكري للمنطقة.' },
  { id: 48, category: 'rare', title: 'بندقية صيد تراثية (قطعة عرض)', titleEn: 'Heritage Display Hunting Rifle', price: 410, oldPrice: 480, rating: 4.8, reviews: 16, condition: 'مستعمل - قطعة عرض فقط', age: 'يعود لـ 90 عامًا', material: 'خشب ومعدن', origin: 'الكويت', seller: 'بيت التحف الكويتي', featured: false, auction: true, desc: 'قطعة تراثية نادرة للعرض والاقتناء فقط، تعكس تاريخ الصيد والحياة البرية في الكويت القديمة.' },
  { id: 49, category: 'rare', title: 'طبق فضي مذهّب بنقوش إسلامية', titleEn: 'Gilded Silver Plate with Islamic Motifs', price: 175, oldPrice: 210, rating: 4.9, reviews: 18, condition: 'مستعمل - حالة ممتازة', age: 'يعود لـ 65 عامًا', material: 'فضة مذهبة', origin: 'الكويت والمنطقة', seller: 'يعقوب الصايغ', featured: false, auction: false, desc: 'طبق فضي فاخر مطلي بالذهب ومزين بنقوش إسلامية هندسية بديعة، قطعة اقتناء راقية.' },
  { id: 50, category: 'rare', title: 'مسبحة كهرمان أصلية نادرة', titleEn: 'Rare Genuine Amber Prayer Beads', price: 145, oldPrice: 175, rating: 4.9, reviews: 23, condition: 'مستعمل - حالة ممتازة', age: 'يعود لـ 50 عامًا', material: 'كهرمان طبيعي', origin: 'المنطقة', seller: 'ناصر الفضلي', featured: true, auction: false, desc: 'مسبحة كهرمان أصلية نادرة بحبات كبيرة صافية، من أرقى أنواع الكهرمان المتداولة قديمًا في الخليج.' },
  { id: 51, category: 'rare', title: 'ختم شخصي فضي قديم', titleEn: 'Old Personal Silver Seal Stamp', price: 68, oldPrice: null, rating: 4.5, reviews: 10, condition: 'مستعمل - حالة جيدة', age: 'يعود لـ 70 عامًا', material: 'فضة', origin: 'الكويت', seller: 'يعقوب الصايغ', featured: false, auction: false, desc: 'ختم شخصي فضي كان يستخدم للتوقيع على الوثائق والرسائل الرسمية في الكويت القديمة.' },
  { id: 52, category: 'rare', title: 'صندوق نقود خشبي بقفل يدوي', titleEn: 'Wooden Money Box with Manual Lock', price: 82, oldPrice: 98, rating: 4.6, reviews: 12, condition: 'مستعمل - حالة جيدة جدًا', age: 'يعود لـ 60 عامًا', material: 'خشب وحديد', origin: 'الكويت', seller: 'بيت التحف الكويتي', featured: false, auction: false, desc: 'صندوق خشبي متين بآلية قفل يدوية تقليدية، كان يستخدم لحفظ النقود والمستندات المهمة.' },
];

// ---------- توليد الصور لكل منتج (3 صور لكل منتج) ----------
PRODUCTS.forEach((p) => {
  const cat = CATEGORIES.find((c) => c.id === p.category);
  const bg = cat ? cat.color : 'C6952C';
  p.images = [ph(p.title, bg, 1), ph(p.title, bg, 2), ph(p.title, bg, 3)];
  p.image = p.images[0];
  p.sellerAvatar = `https://placehold.co/100x100/6B4423/FDF8EE?text=${encodeURIComponent(p.seller.split(' ')[0])}&font=tajawal`;
});

// ---------- تعليقات/تقييمات تجريبية ----------
const REVIEWS_POOL = [
  { name: 'عبدالرحمن العنزي', text: 'قطعة رائعة وأصلية، وصلت بحالة ممتازة تمامًا كما في الوصف. تعامل ممتاز مع البائع.', stars: 5 },
  { name: 'لطيفة الديحاني', text: 'جودة عالية وتغليف ممتاز، سعيدة جدًا بهذه القطعة التراثية النادرة.', stars: 5 },
  { name: 'فهد المري', text: 'المنتج جميل لكن وصل متأخرًا قليلاً عن الموعد المتوقع. بخلاف ذلك كل شيء ممتاز.', stars: 4 },
  { name: 'شيخة القطان', text: 'أفضل من توقعت! التفاصيل اليدوية مذهلة وتستحق كل قرش.', stars: 5 },
  { name: 'سالم البلوشي', text: 'قطعة جميلة، لكن كنت أتمنى لو كانت الصور أوضح قليلاً قبل الشراء.', stars: 4 },
];
